### ISSUE TITLE
Checkstyle fails on Windows saying there is aren't new lines at the end of the java files

### ISSUE THREAD

**Issue by davidcorbin** [davidcorbin/mygcc-api#13]
## Expected Behavior
The build should be successful

## Actual Behavior
Maven install fails

## Steps to Reproduce the Problem

  1. `mvn install`

## Specifications

  - Version: 0.3 (latest)
  - Platform: Windows (x86)

**Comment by mph121** [comment]
Do we really need to compile this on windows tho

**Comment by davidcorbin** [comment]
Proposal to tag as `wontfix`?
